#server:
  #port: 8082

spring:
  config:
    import: optional:classpath:/rabbit-queues.yml
  rabbitmq:
    host: localhost
    port: 5672
    username: coregate
    password: coregate

#  grpc:
#    host: localhost
#    port: 8090