server:
  port: 8082

spring:
  config:
    import:
      - optional:classpath:/application-rabbit.yml

coregate:
  ingress:
    port: 8583

grpc:
  server:
    host: localhost
    port: 8090
  context:
    host: localhost
    port: 8090
