server:
  port: 8084

spring:
  application:
    name: mock-issuer
  config:
    import: optional:classpath:/application-infrastructure.yml

grpc:
  server:
    host: localhost
    port: 8091
  client:
    host: localhost
    port: 8092
