server:
  port: 8085

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: coregate
    password: coregate
  config:
    import:
      - optional:classpath:application-rabbit.yml
      - optional:classpath:queues-rabbit.yml
      - optional:classpath:application-redis.yml
      - optional:classpath:/resilience4j.yml

  cloud:
    openfeign:
      compression:
        request:
          enabled: true
        response:
          enabled: true
      client:
        config:
          issuerClient:
            connectTimeout: 2000
            readTimeout: 2500
            loggerLevel: full

coregate:
  issuer:
    url: http://localhost:1110
    endpoint-authorize: /api/v1/issuer/authorize
    health-max-fails: 3
    health-interval-ms: 300000

grpc:
  server:
    port: 8092
    threads: 64
