server:
  port: 8084

spring:
  application:
    name: coregate-orchestrator
  config:
    import:
      - optional:classpath:management.yml
      - optional:classpath:metrics.yml
      - optional:classpath:queues-rabbit.yml
      - optional:classpath:application-redis.yml
      - optional:classpath:application-rabbit.yml

grpc:
  server:
    port: 8091
    threads: 64

  finalizer:
    host: localhost
    port: 8092
  rules:
    host: localhost
    port: 8093
