server:
  port: 8084

spring:
  application:
    name: mock-issuer
  config:
    import:
      - classpath:management.yml
      - classpath:metrics.yml
      - classpath:queues-rabbit.yml
      - classpath:application-rabbit.yml

grpc:
  server:
    port: 8091
    threads: 64

  finalizer:
    host: localhost
    port: 8092
  rules:
    host: localhost
    port: 8093
